In [ ]:
import pandas as pd
# 1 dimentional Series
mobiles = pd.Series(["iPhone","Nokia","Samsung","OPPO"])
mobiles

0     iPhone
1      Nokia
2    Samsung
3       OPPO
dtype: object

In [20]:
# 1 dimentional Series 
bag = pd.Series(["pens","pencils","notebooks","papers"])
bag

0         pens
1      pencils
2    notebooks
3       papers
dtype: object

In [21]:
# 2 dimentional data
data_frame = pd.DataFrame({"Electronics":mobiles,"Items":bag})
data_frame

  Electronics      Items
0      iPhone       pens
1       Nokia    pencils
2     Samsung  notebooks
3        OPPO     papers

In [27]:
# How to import Data 
# Most common Files Format CSV Comma Seprated Values

# import 
heart_disease_data = pd.read_csv("../Data/heart.csv")
heart_disease_data.head(9)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0

In [ ]:
# export
heart_disease_data.to_csv("modified_heart_disease_data.csv")

In [29]:
# again import 
heart_disease_data = pd.read_csv("../Data/modified_heart_disease_data.csv")
heart_disease_data.head(9)

,Unnamed: 0,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0

In [ ]:
# if you don't want to add index you just write :
heart_disease_data.to_csv("modified_heart_disease_data_2.csv", index = False)
heart_disease_data = pd.read_csv("modified_heart_disease_data_2.csv")
heart_disease_data.head(9)
# if you don't add index = False then its add more index line

How to Describe data

In [4]:
# Attributes

# attribute is not a function
# attribute is not followed by paranthesis
# examples :

heart = pd.read_csv("../Data/heart.csv")

heart.dtypes

columns = heart.columns
columns

index = heart.index
index

# Functions
# function is followed by paranthesis
# examples :

heart.describe() # works only for numerical data
heart.info()
heart.mean() # works only for numerical data

# Finished

# Next

heart["age"]

heart["age"].mean()

heart["age"].sum()

heart["age"].max()

heart["age"].min()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

29

Data Selection

In [27]:
heart.head() # default 5 rows
heart.tail() # default 5 rows

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

Index or Location

In [43]:
# Index (.loc) or Location (.iloc)
birds =  pd.Series(["sparrow","crow","pigeon","eagle"], index = ["a","b","c","d"])
birds

# using index

birds.loc['c'] # indexing

# using location

birds.iloc[2] # positioning

# slicing

birds.iloc[:3] # first 3 rows

# head() = iloc[]

birds.head(3)

# Same 

heart['target']

heart.target

# but there is a difference 
# if heading contains space then you can't use . Attribute

heart[heart['age'] >= 50] # condition

# it does not work on object data type

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017,53,1,0,123,282,0,1,95,1,2.0,1,2,3,0
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [48]:
# crosstab() is used to combine two column

pd.crosstab(heart['age'], heart['target'])

# To compare more than two columns we can use a command groupby

heart.groupby(['age']).mean()
# it only works on numeric data
# heart.dtypes

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,,,,,,,,,,,,,
29,1.000000,1.000000,130.000000,204.000000,0.000000,0.000000,202.000000,0.000000,0.000000,2.000000,0.000000,2.000000,1.000000
34,0.500000,2.000000,118.000000,196.000000,0.000000,0.500000,183.000000,0.000000,0.350000,2.000000,0.000000,2.000000,1.000000
35,0.733333,0.266667,126.533333,209.200000,0.000000,0.800000,160.800000,0.466667,0.800000,1.733333,0.000000,2.466667,0.533333
37,0.500000,2.000000,125.000000,232.500000,0.000000,1.000000,178.500000,0.000000,1.750000,1.000000,0.000000,2.000000,1.000000
38,1.000000,2.333333,132.000000,193.666667,0.000000,1.000000,176.000000,0.333333,1.266667,1.666667,2.666667,2.333333,0.666667
39,0.500000,1.428571,123.285714,236.857143,0.000000,0.785714,160.785714,0.000000,0.342857,1.428571,0.000000,2.285714,0.714286
40,1.000000,0.818182,133.454545,196.090909,0.000000,0.636364,155.818182,0.636364,1.109091,1.636364,0.000000,3.000000,0.272727
41,0.625000,1.187500,119.531250,218.156250,0.000000,0.625000,164.218750,0.093750,0.318750,1.781250,0.093750,1.968750,0.906250
42,0.769231,1.230769,127.461538,246.807692,0.115385,0.769231,158.500000,0.153846,0.530769,1.384615,0.230769,1.961538,0.846154
43,0.730769,0.461538,126.346154,256.923077,0.269231,0.576923,152.807692,0.423077,1.411538,1.346154,0.576923,2.538462,0.576923
44,0.833333,1.166667,120.666667,220.000000,0.000000,0.666667,168.166667,0.194444,0.419444,1.611111,0.250000,1.972222,0.722222
45,0.600000,0.760000,122.680000,246.840000,0.000000,0.240000,156.640000,0.360000,0.624000,1.240000,0.360000,2.240000,0.760000
46,0.608696,0.782609,128.173913,234.608696,0.130435,0.565217,148.565217,0.434783,1.104348,1.304348,0.347826,2.478261,0.521739
47,1.000000,1.222222,119.000000,248.166667,0.000000,0.611111,149.611111,0.222222,0.238889,1.777778,0.222222,2.000000,0.555556
48,0.869565,0.826087,123.913043,250.130435,0.304348,0.434783,165.652174,0.173913,0.291304,1.391304,0.608696,2.478261,0.521739
49,0.647059,1.294118,125.529412,221.529412,0.000000,0.764706,149.882353,0.000000,0.764706,1.588235,1.411765,2.235294,0.529412
50,0.571429,1.000000,130.428571,227.000000,0.000000,0.571429,151.285714,0.142857,0.971429,1.428571,0.142857,2.428571,0.571429
51,0.692308,1.410256,123.487179,257.948718,0.076923,0.538462,149.128205,0.615385,1.241026,1.666667,0.487179,2.358974,0.743590
52,0.930233,1.116279,129.767442,226.348837,0.372093,0.837209,167.348837,0.162791,0.388372,1.674419,0.906977,2.093023,0.651163
53,0.653846,0.692308,132.538462,234.192308,0.384615,0.153846,137.000000,0.423077,0.969231,1.192308,0.653846,2.192308,0.692308
54,0.716981,1.018868,127.698113,253.905660,0.113208,0.433962,146.132075,0.339623,0.964151,1.415094,0.641509,2.452830,0.603774
55,0.500000,0.333333,142.766667,282.266667,0.000000,1.033333,138.400000,0.666667,2.033333,1.100000,0.400000,2.533333,0.333333
56,0.743590,0.794872,135.333333,258.871795,0.410256,0.179487,145.128205,0.564103,1.374359,0.871795,0.641026,2.282051,0.435897
57,0.789474,0.543860,136.315789,241.877193,0.122807,0.614035,143.315789,0.456140,0.735088,1.403509,0.754386,2.368421,0.368421
58,0.691176,0.808824,128.397059,253.794118,0.220588,0.397059,147.250000,0.235294,1.389706,1.367647,1.264706,2.397059,0.352941
59,0.934783,1.282609,148.630435,238.282609,0.217391,0.521739,148.152174,0.347826,1.054348,1.304348,0.543478,2.282609,0.326087
60,0.648649,0.810811,132.000000,245.189189,0.189189,0.459459,149.108108,0.459459,1.659459,1.459459,1.216216,2.648649,0.270270
61,0.741935,0.580645,137.741935,243.774194,0.096774,0.483871,145.387097,0.612903,1.735484,1.387097,0.774194,2.516129,0.096774
62,0.351351,0.567568,133.891892,256.486486,0.162162,0.540541,133.324324,0.162162,1.829730,1.000000,1.324324,2.459459,0.351351
63,0.468750,0.562500,133.250000,263.093750,0.218750,0.312500,152.968750,0.468750,1.840625,1.343750,1.562500,2.406250,0.281250
64,0.735294,1.264706,138.794118,274.970588,0.000000,0.588235,133.235294,0.500000,1.088235,1.176471,0.558824,2.323529,0.558824
65,0.518519,1.111111,138.777778,276.185185,0.259259,0.222222,145.259259,0.000000,1.148148,1.555556,1.074074,2.296296,0.444444
66,0.560000,0.800000,146.960000,244.240000,0.160000,0.400000,140.120000,0.440000,0.904000,1.200000,1.000000,1.880000,0.560000
67,0.709677,0.645161,129.096774,280.870968,0.096774,0.419355,132.838710,0.354839,1.051613,1.193548,1.322581,2.451613,0.290323
68,0.750000,1.500000,140.500000,238.750000,0.500000,0.500000,139.250000,0.250000,1.875000,1.250000,0.750000,2.750000,0.500000
69,0.666667,2.666667,146.666667,242.333333,0.333333,0.333333,142.666667,0.000000,1.300000,1.333333,2.000000,2.333333,0.666667
70,1.000000,0.642857,146.285714,251.857143,0.000000,0.500000,121.500000,0.500000,2.050000,0.928571,1.071429,2.500000,0.214286
71,0.000000,1.000000,124.363636,232.909091,0.363636,0.636364,136.909091,0.000000,0.690909,1.636364,0.909091,2.000000,1.000000
74,0.000000,1.000000,120.000000,269.000000,0.000000,0.000000,121.000000,1.000000,0.200000,2.000000,1.000000,2.000000,1.000000
76,0.000000,2.000000,140.000000,197.000000,0.000000,2.000000,116.000000,0.000000,1.100000,1.000000,0.000000,2.000000,1.000000
77,1.000000,0.000000,125.000000,304.000000,0.000000,0.000000,162.000000,1.000000,0.000000,2.000000,3.000000,2.000000,0.000000

In [ ]:
#  How to plot data

%matplotlib inline
import matplotlib.pyplot as mpl

# heart['age'].plot()

In [ ]:
# this is also not run because of memory 

# heart['age'].hist()

In [1]:
# Now we want to plot object type data

import pandas as pd
%matplotlib inline
import matplotlib.pyplot as mpl

phone = pd.read_csv("../Data/phone.csv")

price_int = phone['price_pkr'].str.replace("Rs.","").astype(int)
# price_int.hist() # due to memory issue I'm unable to run it
price_int

0    195000
1    520000
2     55000
3     48000
4     39000
5     42000
6     62000
7     58000
8     95000
9    115000
Name: price_pkr, dtype: int64

Changing Data

In [7]:
phone['condition'].str.lower()
phone

     brand          model  storage_gb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23         256       8  Rs.195000       New
1    Apple      iPhone 17         512       8  Rs.520000      Used
2   Xiaomi  Redmi Note 13         256       8   Rs.55000       New
3  Infinix        Note 40         256      12   Rs.48000       New
4   Realme            C67         128       8   Rs.39000       New
5    Tecno       Camon 30         256       8   Rs.42000      Used
6     Vivo           Y200         128       8   Rs.62000       New
7     Oppo            A78         256       8   Rs.58000      Used
8  OnePlus      Nord CE 3         256      12   Rs.95000       New
9   Google        Pixel 7         128       8  Rs.115000      Used

In [17]:
# Import Mising values file

import pandas as pd

phone_mv = pd.read_csv("../Data/mising_values_phone.csv")
phone_mv # mv means mising values

phone_mv['ram_gb'].mean()

# phone_mv['ram_gb'].fillna(phone_mv['ram_gb'].mean()) # this not change original file
# phone_mv['ram_gb'].fillna(phone_mv['ram_gb'].mean(), inplace = True)

# Another and safe way

phone_mv['ram_gb'] = phone_mv['ram_gb'].fillna(phone_mv['ram_gb'].mean())

In [27]:
phone_mv = phone_mv.dropna() # drop all rows which contain missing values
phone_mv # now we have only one option to get back our data with NaN values (importing it again)

    brand          model  storage_gb    ram_gb price_pkr condition
2  Xiaomi  Redmi Note 13       256.0  8.000000  Rs.55000       New
6    Vivo           Y200       128.0  8.571429  Rs.62000       New

Remove and Add Data

In [48]:
colour = pd.Series(["Black","Blue"], index = [2,6])

phone_mv['Colour'] = colour
phone_mv

# difference btw list and Series()

variants = [2,3] # if no of columns in data != list entries then it cause but Series() add NaN values in empty place.
phone_mv['variants'] = variants
phone_mv


phone_mv['product'] = phone_mv['variants'] * phone_mv['ram_gb']
phone_mv


phone_mv['new'] = 3
phone_mv

phone_mv['bool'] = True
phone_mv


phone_mv['new'] = 3
phone_mv.drop('new', axis = 1, inplace = True) 

# Axis = 1 for column and Axis = 0 for row

phone_mv

,brand,model,storage_gb,ram_gb,price_pkr,condition,Colour,variants,product,bool
2,Xiaomi,Redmi Note 13,256.0,8.000000,Rs.55000,New,Black,2,16.000000,True
6,Vivo,Y200,128.0,8.571429,Rs.62000,New,Blue,3,25.714286,True

Data Manipulating :

In [5]:
import pandas as pd
phone = pd.read_csv("../Data/phone.csv")
phone.sample(frac=0.5) # 50 % shufling
phone.sample(frac = 0) # 0% shufling
phone.sample(frac = 1) # 100% shufling
phone.reset_index(drop=True,inplace = True)
phone

# Now we want to change the storage_gb to storage_tb

# phone_mv['storage_gb'] = phone_mv['storage_gb'] / 1024
phone['storage_gb'] = phone['storage_gb'].apply(lambda x : x / 1024)
phone.columns = phone.columns.str.replace('storage_gb', 'storage_tb')   
phone

     brand          model  storage_tb  ram_gb  price_pkr condition
0  Samsung     Galaxy S23       0.250       8  Rs.195000       New
1    Apple      iPhone 17       0.500       8  Rs.520000      Used
2   Xiaomi  Redmi Note 13       0.250       8   Rs.55000       New
3  Infinix        Note 40       0.250      12   Rs.48000       New
4   Realme            C67       0.125       8   Rs.39000       New
5    Tecno       Camon 30       0.250       8   Rs.42000      Used
6     Vivo           Y200       0.125       8   Rs.62000       New
7     Oppo            A78       0.250       8   Rs.58000      Used
8  OnePlus      Nord CE 3       0.250      12   Rs.95000       New
9   Google        Pixel 7       0.125       8  Rs.115000      Used